### ISSUE TITLE
Contribute the code to the spdx-licenses project

### ISSUE THREAD

**Issue by sschuberth** [librariesio/spdx#2]
How about contributing this code directly to [spdx-licenses](https://github.com/domcleal/spdx-licenses), so in addition to its

```
lic = SpdxLicenses.lookup('Apache-2.0')
```

it would get something like

```
lic = SpdxLicenses.fuzzyLookup('Apache 2')
```

or

```
lic = SpdxLicenses.lookup('Apache 2', :fuzzy => true)
```

?

**Comment by domcleal** [comment]
Yep, sounds like a great idea.  I wasn't aware of this project, it looks interesting.  If you'd like, please go ahead and propose a PR, I'll review it as soon as I can, and would be happy to share maintainership of the gem too.

It would be a good basis for future support in spdx-licenses for parsing more complex licence types (Foo and Bar, etc).

**Comment by andrew** [comment]
Ok great, I've extracted most of the code from https://libraries.io to handle all the weird edge cases and spellings, at the moment I split license names by `,` and `/`which seems to cover a lot of cases.

**Comment by sschuberth** [comment]
@andrew Do you still plan to submit a PR to @domcleal's project any time soon?

**Comment by andrew** [comment]
@sschuberth at the moment I don't have any free time to work on that, having both projects separate allows me to move more quickly on my Libraries.io work, it's available under MIT so anyone else is welcome to combine them if they wish
