### ISSUE TITLE
Incorrect normalization of commercial licenses in cocoapods?

### ISSUE THREAD

**Issue by tieguy** [librariesio/spdx#42]
Cocoapods (among others) is reporting a lot of CC-BY-NC-4.0. Checking that against their website reveals a lot of packages that they think of as "commercial" rather than CC-BY-NC-4.0 specifically.

A few examples:
https://cocoapods.org/pods/Flurry-iOS-SDK
https://cocoapods.org/pods/ProRTC

I have more if you need them.

**Comment by andrew** [comment]
Good spot, two bugs for the price of one!

In some cases in Libraries.io for cocoapods we were saving a hash like `"license": {"type": "Commercial","file": "Licenses/Flurry-LICENSE.txt"}` and then passing that to spdx, which got confused, fix here: https://github.com/librariesio/libraries.io/pull/1938

In other cases the plain word `Commercial` matched to `Creative Commons Attribution Non Commercial 2.0` in the fuzzy_matcher, I've added an explicit clause for `Commercial in https://github.com/librariesio/spdx/pull/43

**Comment by andrew** [comment]
Merged and released in v1.3.3, will be deploying to Libraries shortly and then renormalizing all the "CC-BY-NC-4.0" licensed projects.

**Comment by andrew** [comment]
🚢
